apiVersion: apps/v1
kind: Deployment
metadata:
  name: observability-demo
  namespace: observability-demo
  labels:
    app: observability-demo

spec:
  replicas: 2

  selector:
    matchLabels:
      app: observability-demo

  template:
    metadata:
      labels:
        app: observability-demo

    spec:
      imagePullSecrets:
        - name: ghcr-secret

      containers:
        - name: app
          image: ghcr.io/touhiddevops/k8s-observability-demo:1.0
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          resources:
            requests:
              cpu: 100m
              memory: 128Mi

            limits:
              cpu: 500m
              memory: 256Mi

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
