apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: observability


data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Log_Level    info

    [INPUT]
        Name         tail
        Path         /var/log/containers/*.log
        Parser       cri
        Tag          kube.*
        Mem_Buf_Limit 10MB
        Skip_Long_Lines On

    [OUTPUT]
        Name            es
        Match           *
        Host            elasticsearch.observability.svc.cluster.local
        Port            9200
        Index           kubernetes-logs
        Logstash_Format On
        Suppress_Type_Name On
