apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-demo
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/touhiddevops/k8s-observability-demo.git
    targetRevision: main
    path: manifests/app

  destination:
    server: https://kubernetes.default.svc
    namespace: observability-demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
